from django.urls import path

from .views import (
    AnalysisOrderCreateView,
    AnalysisOrderDetailView,
    AnalysisOrderEditView,
    AnalysisOrderListView,
    AnalysisSamplesFrontendView,
    AnalysisSamplesListView,
    CloneOrderActionView,
    ConfirmOrderActionView,
    EquipmentOrderCreateView,
    EquipmentOrderDetailView,
    EquipmentOrderEditView,
    EquipmentOrderListView,
    EquipmentOrderQuantityUpdateView,
    ExtractionOrderCreateView,
    ExtractionOrderDetailView,
    ExtractionOrderEditView,
    ExtractionOrderListView,
    GenrequestAnalysisOrderListView,
    GenrequestCreateView,
    GenrequestDeleteView,
    GenrequestDetailView,
    GenrequestEquipmentOrderListView,
    GenrequestExtractionOrderListView,
    GenrequestListView,
    GenrequestOrderDeleteView,
    GenrequestOrderListView,
    GenrequestUpdateView,
    OrderListView,
    SamplesFrontendView,
    SamplesListView,
)

appname = "genlab_bestilling"
urlpatterns = [
    path(
        "genrequests/",
        GenrequestListView.as_view(),
        name="genrequest-list",
    ),
    path(
        "orders/",
        OrderListView.as_view(),
        name="order-list",
    ),
    path(
        "orders/extraction/",
        ExtractionOrderListView.as_view(),
        name="order-extraction-list",
    ),
    path(
        "orders/analysis/",
        AnalysisOrderListView.as_view(),
        name="order-analysis-list",
    ),
    path(
        "orders/equipment/",
        EquipmentOrderListView.as_view(),
        name="order-equipment-list",
    ),
    path(
        "genrequests/create/",
        GenrequestCreateView.as_view(),
        name="genrequest-create",
    ),
    path(
        "genrequests/<int:pk>/",
        GenrequestDetailView.as_view(),
        name="genrequest-detail",
    ),
    path(
        "genrequests/<int:pk>/update/",
        GenrequestUpdateView.as_view(),
        name="genrequest-update",
    ),
    path(
        "genrequests/<int:pk>/delete/",
        GenrequestDeleteView.as_view(),
        name="genrequest-delete",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/",
        GenrequestOrderListView.as_view(),
        name="genrequest-order-list",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/equipment/",
        GenrequestEquipmentOrderListView.as_view(),
        name="genrequest-equipment-list",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/extraction/",
        GenrequestExtractionOrderListView.as_view(),
        name="genrequest-extraction-list",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/analysis/",
        GenrequestAnalysisOrderListView.as_view(),
        name="genrequest-analysis-list",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/<int:pk>/clone/",
        CloneOrderActionView.as_view(),
        name="genrequest-order-clone",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/equipment/create/",
        EquipmentOrderCreateView.as_view(),
        name="genrequest-equipment-create",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/equipment/<int:pk>/",
        EquipmentOrderDetailView.as_view(),
        name="genrequest-equipment-detail",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/equipment/<int:pk>/delete/",
        GenrequestOrderDeleteView.as_view(),
        name="genrequest-equipment-delete",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/equipment/<int:pk>/update/",
        EquipmentOrderEditView.as_view(),
        name="genrequest-equipment-update",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/equipment/<int:pk>/quantity/",
        EquipmentOrderQuantityUpdateView.as_view(),
        name="genrequest-equipment-quantity-update",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/analysis/create/",
        AnalysisOrderCreateView.as_view(),
        name="genrequest-analysis-create",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/analysis/<int:pk>/",
        AnalysisOrderDetailView.as_view(),
        name="genrequest-analysis-detail",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/analysis/<int:pk>/update/",
        AnalysisOrderEditView.as_view(),
        name="genrequest-analysis-update",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/analysis/<int:pk>/delete/",
        GenrequestOrderDeleteView.as_view(),
        name="genrequest-analysis-delete",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/analysis/<int:pk>/samples/",
        AnalysisSamplesListView.as_view(),
        name="genrequest-analysis-samples",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/analysis/<int:pk>/samples/edit/",
        AnalysisSamplesFrontendView.as_view(),
        name="genrequest-analysis-samples-edit",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/extraction/create/",
        ExtractionOrderCreateView.as_view(),
        name="genrequest-extraction-create",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/extraction/<int:pk>/",
        ExtractionOrderDetailView.as_view(),
        name="genrequest-extraction-detail",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/extraction/<int:pk>/update/",
        ExtractionOrderEditView.as_view(),
        name="genrequest-extraction-update",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/extraction/<int:pk>/delete/",
        GenrequestOrderDeleteView.as_view(),
        name="genrequest-extraction-delete",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/extraction/<int:pk>/samples/",
        SamplesListView.as_view(),
        name="genrequest-extraction-samples",
    ),
    path(
        "genrequests/<int:genrequest_id>/orders/extraction/<int:pk>/samples/edit/",
        SamplesFrontendView.as_view(),
        name="genrequest-extraction-samples-edit",
    ),
    # Actions
    path(
        "genrequests/<int:genrequest_id>/orders/<int:pk>/confirm/",
        ConfirmOrderActionView.as_view(),
        name="genrequest-order-confirm",
    ),
]
