# Changes here will be overwritten by Copier
_commit: v0.0.1
_src_path: gh:ninanor/python-template
author_name: Niccolò Cantù
default_branch_name: main
email: niccolo.cantu@nina.no
gis: false
ldap: false
project_name: GenLab Bestilling System
project_slug: genlab_bestilling
repo_name: genlab_bestilling
repo_org: ninanor
rest: true
template_type: django
type_annotations: false
ui: false
