# Generated by Django 5.0.7 on 2024-07-25 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genrequest",
            options={"verbose_name": "Genetic Request"},
        ),
        migrations.AlterModelOptions(
            name="species",
            options={"verbose_name_plural": "Species"},
        ),
    ]
