# Generated by Django 5.1.4 on 2025-01-09 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysistype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="area",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="marker",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="sampletype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="species",
            options={"ordering": ["name"], "verbose_name_plural": "Species"},
        ),
    ]
