# Generated by Django 5.1.1 on 2024-09-10 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0002_alter_genrequest_options_alter_species_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="markers",
        ),
    ]
