# Generated by Django 5.0.6 on 2024-06-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0002_order_name_order_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
