# Generated by Django 5.1.4 on 2025-01-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0003_analysisresult_order_alter_species_markers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="samples",
                to="genlab_bestilling.extractionorder",
            ),
        ),
    ]
