# Generated by Django 5.0.6 on 2024-06-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0004_alter_equimentorderquantity_equipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="species",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="genlab_bestilling.species"
            ),
        ),
    ]
