# Generated by Django 5.1.1 on 2024-10-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0004_remove_sample_date_sample_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="station_id",
            new_name="code",
        ),
        migrations.AddField(
            model_name="location",
            name="fylke",
            field=models.CharField(blank=True, null=True),
        ),
    ]
