# Generated by Django 5.1.4 on 2025-01-21 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0004_alter_sample_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genrequest",
            options={"verbose_name": "Genetic Project"},
        ),
        migrations.AlterField(
            model_name="order",
            name="genrequest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="genlab_bestilling.genrequest",
                verbose_name="Genetic Project",
            ),
        ),
    ]
