# Generated by Django 5.1.4 on 2025-01-23 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0005_alter_genrequest_options_alter_order_genrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentBuffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("unit", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="equimentorderquantity",
            name="buffer_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equimentorderquantity",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="genlab_bestilling.equipmenttype",
            ),
        ),
        migrations.AlterField(
            model_name="equimentorderquantity",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14),
        ),
        migrations.AddField(
            model_name="equimentorderquantity",
            name="buffer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_quantities",
                to="genlab_bestilling.equipmentbuffer",
            ),
        ),
    ]
