# Generated by Django 5.0.6 on 2024-06-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0005_alter_project_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("confirmed", "Confirmed")],
                default="draft",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="genlab_bestilling.project",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="samples",
                to="genlab_bestilling.analysisorder",
            ),
        ),
    ]
