# Generated by Django 5.1.3 on 2024-12-03 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0006_genrequest_created_at_genrequest_last_modified_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                ("analysis_date", models.DateTimeField(blank=True, null=True)),
                ("result_file", models.FileField(blank=True, null=True, upload_to="")),
                ("extra", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExtractionPlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                ("extracted_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ExtractPlatePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="sample",
            name="desired_extractions",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="sample",
            name="genlab_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="genlab_bestilling.sample",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="code",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("confirmed", "Confirmed"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("checked", "Checked"),
                    ("extracted", "Extracted"),
                ],
                default="draft",
            ),
        ),
        migrations.AddConstraint(
            model_name="species",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unique species code"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="marker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="genlab_bestilling.marker",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="samples",
            field=models.ManyToManyField(blank=True, to="genlab_bestilling.sample"),
        ),
        migrations.AddField(
            model_name="sample",
            name="extractions",
            field=models.ManyToManyField(
                blank=True, to="genlab_bestilling.extractionplate"
            ),
        ),
        migrations.AddField(
            model_name="extractplateposition",
            name="plate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sample_positions",
                to="genlab_bestilling.extractionplate",
            ),
        ),
        migrations.AddField(
            model_name="extractplateposition",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plate_positions",
                to="genlab_bestilling.sample",
            ),
        ),
    ]
