# Generated by Django 5.0.6 on 2024-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0006_order_status_alter_order_project_alter_sample_order",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("confirmed", "Confirmed"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                ],
                default="draft",
            ),
        ),
    ]
