# Generated by Django 5.1.4 on 2025-01-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0006_equipmentbuffer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equimentorderquantity",
            name="buffer_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="How much buffer do you need? the value should be in uL",
                max_digits=14,
                null=True,
                verbose_name="Buffer volume",
            ),
        ),
    ]
