# Generated by Django 5.0.6 on 2024-06-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0007_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="area",
        ),
        migrations.AlterField(
            model_name="sample",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="genlab_bestilling.location",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
