# Generated by Django 5.1.3 on 2024-12-03 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0007_analysis_extractionplate_extractplateposition_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE or replace FUNCTION generate_genlab_id(species_code varchar, year integer) RETURNS varchar
                LANGUAGE plpgsql
                AS $$
            begin
            execute format('create sequence if not exists seq_G%s%s', year, species_code);
            return 'G' || year % 100 || species_code || LPAD(nextval(format('seq_G%s%s', year, species_code))::text, 5, '0');
            end
            $$;

            CREATE or replace FUNCTION generate_replica(genlab_id varchar) RETURNS varchar
                LANGUAGE plpgsql
                AS $$
            begin
            execute format('create sequence if not exists rep_%s maxvalue 26', genlab_id);
            return genlab_id || CHR(64 + nextval(format('rep_%s', genlab_id))::integer);
            end
            $$;
        """,
            """
            DROP FUNCTION generate_genlab_id(species_code varchar, year integer);
            DROP FUNCTION generate_replica(genlab_id varchar);
        """,
        )
    ]
