# Generated by Django 5.1.1 on 2024-12-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0007_analysis_extractionplate_extractplateposition_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("confirmed", "Confirmed"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("checked", "Checked"),
                    ("extracted", "Extracted"),
                ],
                default="draft",
            ),
        ),
    ]
