# Generated by Django 5.1.5 on 2025-03-11 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0007_alter_equimentorderquantity_buffer_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisorder",
            name="customize_markers",
        ),
    ]
