# Generated by Django 5.1.5 on 2025-03-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0008_remove_analysisorder_customize_markers"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisorder",
            name="expected_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
