# Generated by Django 5.1.3 on 2024-12-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0008_generate_genlabid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genrequest",
            name="expected_total_samples",
        ),
        migrations.AddField(
            model_name="analysisorder",
            name="expected_total_samples",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="extractionplate",
            name="extracted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
