# Generated by Django 5.0.6 on 2024-06-28 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0008_remove_sample_area_alter_sample_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="markers",
            field=models.ManyToManyField(blank=True, to="genlab_bestilling.marker"),
        ),
        migrations.AlterField(
            model_name="sample",
            name="pop_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="genlab_bestilling.sampletype",
            ),
        ),
    ]
