# Generated by Django 5.0.6 on 2024-07-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0009_alter_sample_markers_alter_sample_pop_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisorder",
            name="markers",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="genlab_bestilling.marker"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="sample_types",
            field=models.ManyToManyField(
                related_name="orders", to="genlab_bestilling.sampletype"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="species",
            field=models.ManyToManyField(
                related_name="orders", to="genlab_bestilling.species"
            ),
        ),
    ]
