# Generated by Django 5.1.7 on 2025-03-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0009_analysisorder_expected_delivery_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="location_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="species",
                to="genlab_bestilling.locationtype",
            ),
        ),
    ]
