# Generated by Django 5.1.3 on 2024-12-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0009_remove_genrequest_expected_total_samples_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extractionplate",
            name="extracted_at",
        ),
        migrations.AddField(
            model_name="extractplateposition",
            name="extracted_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="extractionplate",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="extractplateposition",
            constraint=models.UniqueConstraint(
                fields=("plate", "position"), name="unique_positions_in_plate"
            ),
        ),
    ]
