# Generated by Django 5.1.7 on 2025-04-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0010_alter_species_location_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="type",
        ),
        migrations.AddField(
            model_name="location",
            name="types",
            field=models.ManyToManyField(
                blank=True, to="genlab_bestilling.locationtype"
            ),
        ),
    ]
