# Generated by Django 5.1.3 on 2024-12-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0010_remove_extractionplate_extracted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractplateposition",
            name="notes",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="extractplateposition",
            name="sample",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plate_positions",
                to="genlab_bestilling.sample",
            ),
        ),
    ]
