# Generated by Django 5.1.3 on 2024-12-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0011_extractplateposition_notes_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sample",
            constraint=models.UniqueConstraint(
                fields=("genlab_id",), name="unique_genlab_id"
            ),
        ),
    ]
