# Generated by Django 5.2.3 on 2025-06-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0011_remove_location_type_location_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="river_id",
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
