# Generated by Django 5.0.7 on 2024-07-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0012_project_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
