# Generated by Django 5.2.3 on 2025-06-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0012_alter_location_river_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="This field can be used to store additional information about the location, such as the species in focus or other relevant details.",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="river_id",
            field=models.CharField(
                blank=True,
                help_text="Unique river ID. If the id is taken, a dotted suffix can be utilised. This could be useful for sub locations within the main river. For example, if the main river ID is '1234', a sub location can be '1234.2'.",
                max_length=250,
                null=True,
                unique=True,
            ),
        ),
    ]
