# Generated by Django 5.2.3 on 2025-06-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0013_location_comment_alter_location_river_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Email to contact with questions about this order",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="contact_person",
            field=models.CharField(
                blank=True,
                help_text="Person to contact with questions about this order",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_urgent",
            field=models.BooleanField(
                default=False, help_text="Check this box if the order is urgent"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("confirmed", "Delivered"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                ],
                default="draft",
            ),
        ),
    ]
