# Generated by Django 5.0.7 on 2024-07-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0013_sample_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="river_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="station_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
