# Generated by Django 5.2.3 on 2025-06-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genlab_bestilling', '0013_location_comment_alter_location_river_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
