# Generated by Django 5.2.3 on 2025-06-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0013_location_comment_alter_location_river_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("confirmed", "Delivered"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                ],
                default="draft",
            ),
        ),
    ]
