# Generated by Django 5.2.3 on 2025-06-23 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0014_alter_order_status"),
        ("genlab_bestilling", "0014_order_is_urgent"),
    ]

    operations = []
