# Generated by Django 5.2.3 on 2025-06-30 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0014_order_contact_email_order_contact_person_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="samplemarkeranalysis",
            options={"verbose_name_plural": "Sample marker analyses"},
        ),
    ]
