# Generated by Django 5.0.7 on 2024-07-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0014_alter_location_river_id_alter_location_station_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipmentorder",
            old_name="use_guid",
            new_name="needs_guid",
        ),
        migrations.RemoveField(
            model_name="analysisorder",
            name="has_guid",
        ),
        migrations.AddField(
            model_name="analysisorder",
            name="needs_guid",
            field=models.BooleanField(default=False),
        ),
    ]
