# Generated by Django 5.2.3 on 2025-07-01 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0015_alter_samplemarkeranalysis_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equimentorderquantity",
            options={"verbose_name_plural": "Equipment order quantities"},
        ),
    ]
