# Generated by Django 5.2.3 on 2025-06-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0015_merge_0014_alter_order_status_0014_order_is_urgent",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="is_urgent",
            field=models.BooleanField(
                default=False, help_text="Check this box if the order is urgent"
            ),
        ),
    ]
