# Generated by Django 5.0.7 on 2024-07-24 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0015_rename_use_guid_equipmentorder_needs_guid_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name="area",
            name="location_mandatory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="location",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="genlab_bestilling.locationtype",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="location_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="genlab_bestilling.locationtype",
            ),
        ),
    ]
