# Generated by Django 5.0.7 on 2024-07-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0016_locationtype_area_location_mandatory_location_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="number",
            field=models.CharField(verbose_name="Project number"),
        ),
    ]
