# Generated by Django 5.2.3 on 2025-06-25 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0016_alter_order_is_urgent"),
        ("genlab_bestilling", "0016_order_contact_email_order_contact_person_and_more"),
    ]

    operations = []
