# Generated by Django 5.2.3 on 2025-07-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0017_order_responsible_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisorder",
            name="expected_delivery_date",
            field=models.DateField(
                blank=True,
                help_text="When you need to get the results",
                null=True,
                verbose_name="Requested analysis result deadline",
            ),
        ),
    ]
