# Generated by Django 5.2.3 on 2025-06-27 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0017_merge_20250625_1024"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("ordering", models.IntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_status_list",
                        to="genlab_bestilling.order",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_status_list",
                        to="genlab_bestilling.sample",
                    ),
                ),
            ],
            options={
                "unique_together": {("sample", "order")},
            },
        ),
        migrations.AddField(
            model_name="area",
            name="statuses",
            field=models.ManyToManyField(
                blank=True, related_name="areas", to="genlab_bestilling.samplestatus"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="sample_statuses",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="genlab_bestilling.samplestatus"
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="statuses",
            field=models.ManyToManyField(
                blank=True, related_name="samples", to="genlab_bestilling.samplestatus"
            ),
        ),
        migrations.CreateModel(
            name="AreaSampleStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_sample_statuses",
                        to="genlab_bestilling.area",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_assignments",
                        to="genlab_bestilling.samplestatus",
                    ),
                ),
            ],
            options={
                "unique_together": {("area", "status")},
            },
        ),
        migrations.CreateModel(
            name="SampleStatusAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_status_assignments",
                        to="genlab_bestilling.order",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_status_assignments",
                        to="genlab_bestilling.sample",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_assignments",
                        to="genlab_bestilling.samplestatus",
                    ),
                ),
            ],
            options={
                "unique_together": {("sample", "status", "order")},
            },
        ),
    ]
