# Generated by Django 5.2.3 on 2025-06-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0018_extractionorder_samples_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractionorder",
            name="samples_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a CSV file with the samples to extract. ",
                null=True,
                upload_to="",
            ),
        ),
    ]
