# Generated by Django 5.2.3 on 2025-06-27 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0018_samplestatus_area_statuses_order_sample_statuses_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="samplestatus",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="samplestatus",
            name="order",
        ),
        migrations.RemoveField(
            model_name="samplestatus",
            name="sample",
        ),
    ]
