# Generated by Django 5.2.3 on 2025-07-03 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0018_alter_analysisorder_expected_delivery_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="IsolationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SampleStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("weight", models.IntegerField(default=0)),
                (
                    "area",
                    models.ForeignKey(
                        help_text="The area this status is related to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_statuses",
                        to="genlab_bestilling.area",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleStatusAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_status_assignments",
                        to="genlab_bestilling.order",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_status_assignments",
                        to="genlab_bestilling.sample",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_assignments",
                        to="genlab_bestilling.samplestatus",
                    ),
                ),
            ],
            options={
                "unique_together": {("sample", "status", "order")},
            },
        ),
        migrations.AddField(
            model_name="sample",
            name="assigned_statuses",
            field=models.ManyToManyField(
                blank=True,
                related_name="samples",
                through="genlab_bestilling.SampleStatusAssignment",
                to="genlab_bestilling.samplestatus",
            ),
        ),
    ]
