# Generated by Django 5.2.3 on 2025-07-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0019_isolationmethod_samplestatus_samplestatusassignment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
