# Generated by Django 5.2.3 on 2025-07-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0019_isolationmethod_samplestatus_samplestatusassignment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="is_prioritised",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if the sample is prioritised for processing",
            ),
        ),
    ]
