# Generated by Django 5.2.3 on 2025-07-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0020_sample_is_prioritised"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_prioritized",
            field=models.BooleanField(
                default=False, help_text="If an order should be prioritized internally"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_seen",
            field=models.BooleanField(
                default=False, help_text="If an order has been seen by a staff"
            ),
        ),
    ]
