# Generated by Django 5.2.3 on 2025-07-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0021_order_is_prioritized_order_is_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="internal_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
