# Generated by Django 5.2.3 on 2025-07-08 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0022_sample_internal_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="responsible_staff",
            field=models.ManyToManyField(
                blank=True,
                help_text="Staff members responsible for this order",
                related_name="responsible_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsible staff",
            ),
        ),
    ]
