# Generated by Django 5.2.3 on 2025-07-10 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0023_alter_order_responsible_staff"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="genrequest",
            name="responsible_staff",
            field=models.ManyToManyField(
                blank=True,
                help_text="Staff members responsible for this order",
                related_name="responsible_genrequest",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsible staff",
            ),
        ),
    ]
