# Generated by Django 5.2.3 on 2025-07-09 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0023_alter_order_responsible_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="GIDSequence",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("last_value", models.IntegerField(default=0)),
                ("year", models.IntegerField()),
                (
                    "sample",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replica_sequence",
                        to="genlab_bestilling.sample",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="genlab_bestilling.species",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "species"), name="unique_id_year_species"
                    )
                ],
            },
        ),
    ]
