# Generated by Django 5.2.3 on 2025-07-11 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0025_genrequest_responsible_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplestatusassignment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("marked", "Marked"),
                    ("plucked", "Plucked"),
                    ("isolated", "Isolated"),
                ],
                help_text="The status of the sample in the lab",
                null=True,
                verbose_name="Sample status",
            ),
        ),
        migrations.RemoveField(
            model_name="sample",
            name="assigned_statuses",
        ),
        migrations.AddField(
            model_name="isolationmethod",
            name="species",
            field=models.ForeignKey(
                default=None,
                help_text="The species this isolation method is related to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="species_isolation_methods",
                to="genlab_bestilling.species",
            ),
        ),
        migrations.CreateModel(
            name="SampleIsolationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isolation_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_isolation_methods",
                        to="genlab_bestilling.isolationmethod",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="isolation_methods",
                        to="genlab_bestilling.sample",
                    ),
                ),
            ],
            options={
                "unique_together": {("sample", "isolation_method")},
            },
        ),
        migrations.AddField(
            model_name="sample",
            name="isolation_method",
            field=models.ManyToManyField(
                blank=True,
                help_text="The isolation method used for this sample",
                related_name="samples",
                through="genlab_bestilling.SampleIsolationMethod",
                to="genlab_bestilling.isolationmethod",
            ),
        ),
        migrations.DeleteModel(
            name="SampleStatus",
        ),
    ]
