# Generated by Django 5.2.3 on 2025-07-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0026_alter_samplestatusassignment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="isolationmethod",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
