# Generated by Django 5.2.3 on 2025-07-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0027_alter_isolationmethod_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="is_isolated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sample",
            name="is_marked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sample",
            name="is_plucked",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="SampleStatusAssignment",
        ),
    ]
