# Generated by Django 5.2.3 on 2025-07-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0028_sample_is_isolated_sample_is_marked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contact_email",
            field=models.EmailField(
                help_text="Email to contact with questions about this order",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="contact_person",
            field=models.CharField(
                help_text="Person to contact with questions about this order", null=True
            ),
        ),
    ]
