# Generated by Django 5.2.3 on 2025-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genlab_bestilling', '0029_alter_order_contact_email_alter_order_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='has_pcr',
            field=models.BooleanField(blank=True, default=False, help_text='Check this box if the sample has been processed by PCR', null=True, verbose_name='PCR'),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_analysed',
            field=models.BooleanField(blank=True, default=False, help_text='Check this box if the sample has been analysed', null=True, verbose_name='Analysed'),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_outputed',
            field=models.BooleanField(blank=True, default=False, help_text='Check this box if the sample has an output file', null=True, verbose_name='Output'),
        ),
    ]
