# Generated by Django 5.2.3 on 2025-07-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0031_delete_all_isolationmethods",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="isolationmethod", name="species"),
        migrations.AddField(
            model_name="isolationmethod",
            name="type",
            field=models.ForeignKey(
                to="genlab_bestilling.sampletype",
                on_delete=models.CASCADE,
                related_name="type_isolation_methods",
                help_text="The sample type this isolation method is related to.",
            ),
        ),
    ]
