# Generated by Django 5.2.3 on 2025-07-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0032_alter_isolationmethod_remove_species_add_type_20250722_1226",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="markers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Markers that are relevant for this sample",
                related_name="samples",
                through="genlab_bestilling.SampleMarkerAnalysis",
                to="genlab_bestilling.marker",
            ),
        ),
    ]
