# Generated by Django 5.2.3 on 2025-07-24 15:45

from django.db import migrations
from django.db.migrations.state import StateApps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def delete_isolation_methods(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    IsolationMethod = apps.get_model("genlab_bestilling", "IsolationMethod")
    IsolationMethod.objects.all().delete()


def reverse_delete_isolation_methods(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
):
    pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0033_alter_order_contact_person_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            delete_isolation_methods,
            reverse_delete_isolation_methods,
        ),
    ]
