# Generated by Django 5.2.3 on 2025-07-24 15:49

from django.db import migrations
from django.db.models import ManyToManyField


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0034_delete_all_isolationmethods_20250724_1745"),
    ]

    operations = [
        migrations.RemoveField(model_name="isolationmethod", name="type"),
        migrations.AddField(
            model_name="isolationmethod",
            name="sample_types",
            field=ManyToManyField(
                to="genlab_bestilling.SampleType",
                related_name="isolation_methods",
                verbose_name="Sample types",
                blank=True,
                help_text="Sample types that this isolation method can be used for",
            ),
        ),
    ]
