# Generated by Django 5.2.3 on 2025-07-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0035_add_sample_types_to_isolationmethod_20250724_1749"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="markers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Markers that are relevant for this sample",
                related_name="samples",
                through="genlab_bestilling.SampleMarkerAnalysis",
                to="genlab_bestilling.marker",
            ),
        ),
    ]
