# Generated by Django 5.2.3 on 2025-08-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0037_remove_analysisorderresultscommunication_contact_person_results",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contact_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="contact_person",
            field=models.CharField(null=True),
        ),
    ]
