# Generated by Django 5.2.3 on 2025-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0038_alter_order_contact_email_alter_order_contact_person",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisorder",
            name="metadata_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a metadata file for this analysis order",
                null=True,
                upload_to="analysis_orders/metadata/",
                verbose_name="Metadata file",
            ),
        ),
    ]
