# Generated by Django 5.2.3 on 2025-08-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0039_analysisorder_metadata_file"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="gidsequence",
            name="unique_id_year_species",
        ),
        migrations.AddConstraint(
            model_name="gidsequence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sample", None)),
                fields=("year", "species"),
                name="unique_id_year_species",
            ),
        ),
        migrations.AddConstraint(
            model_name="gidsequence",
            constraint=models.UniqueConstraint(
                fields=("year", "species", "sample"),
                name="unique_id_year_species_sample",
            ),
        ),
    ]
