# Generated by Django 5.2.3 on 2025-08-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0040_remove_gidsequence_unique_id_year_species_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="is_invalid",
            field=models.BooleanField(default=False),
        ),
    ]
