# Generated by Django 5.2.3 on 2025-08-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0041_sample_is_invalid"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplemarkeranalysis",
            name="is_invalid",
            field=models.BooleanField(default=False),
        ),
    ]
