# Generated by Django 5.2.3 on 2025-08-12 09:22

import shared.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0042_samplemarkeranalysis_is_invalid"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisPlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
            ],
            bases=(shared.mixins.AdminUrlsMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="extractplateposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 0), ("position__lte", 95)),
                name="position_in_plate_value_range",
            ),
        ),
    ]
