# Generated by Django 5.2.3 on 2025-08-13 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0042_samplemarkeranalysis_is_invalid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extractplateposition",
            name="plate",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="extractions",
        ),
        migrations.RemoveField(
            model_name="extractplateposition",
            name="sample",
        ),
        migrations.DeleteModel(
            name="AnalysisResult",
        ),
        migrations.DeleteModel(
            name="ExtractionPlate",
        ),
        migrations.DeleteModel(
            name="ExtractPlatePosition",
        ),
    ]
