# Generated by Django 5.2.3 on 2025-09-01 08:10

import genlab_bestilling.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0044_plate_analysisplate_extractionplate_plateposition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisorder",
            name="metadata_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a metadata file for this analysis order",
                null=True,
                upload_to=genlab_bestilling.models.UPLOAD_ANALYSIS_META,
                verbose_name="Metadata file",
            ),
        ),
        migrations.AlterField(
            model_name="analysisplate",
            name="result_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=genlab_bestilling.models.UPLOAD_ANALYSIS_RESULTS,
            ),
        ),
    ]
