# Generated by Django 5.2.3 on 2025-11-20 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0045_alter_analysisorder_metadata_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisplate",
            name="analysis_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="genlab_bestilling.analysistype",
            ),
        ),
        migrations.AddField(
            model_name="analysisplate",
            name="markers",
            field=models.ManyToManyField(blank=True, to="genlab_bestilling.marker"),
        ),
        migrations.AddField(
            model_name="extractionplate",
            name="sample_types",
            field=models.ManyToManyField(blank=True, to="genlab_bestilling.sampletype"),
        ),
        migrations.AddField(
            model_name="extractionplate",
            name="species",
            field=models.ManyToManyField(blank=True, to="genlab_bestilling.species"),
        ),
        migrations.AddField(
            model_name="plateposition",
            name="filled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
