# Generated by Django 5.2.3 on 2025-11-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genlab_bestilling",
            "0046_analysisplate_analysis_type_analysisplate_markers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisorder",
            name="external_samples",
            field=models.BooleanField(default=False),
        ),
    ]
