# Generated by Django 5.2.3 on 2025-11-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0047_analysisorder_external_samples"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionplate",
            name="isolated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
