# Generated by Django 5.2.3 on 2026-03-02 08:13

import sequencefield.constraints
import sequencefield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0049_alter_analysisorder_metadata_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysisplate",
            options={},
        ),
        migrations.AddField(
            model_name="analysisplate",
            name="analysis_number",
            field=sequencefield.fields.IntegerSequenceField(default=-1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="analysisplate",
            constraint=sequencefield.constraints.IntSequenceConstraint(
                drop=True,
                fields=("analysis_number",),
                maxvalue=2147483647,
                name="genlab_bestilling_analysisplate_analysis_number_seq",
                sequence="analysis_number_seq",
                start=1,
            ),
        ),
    ]
