# Generated by Django 5.2.3 on 2026-03-03 11:45

import django.db.models.deletion
import shared.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0050_alter_analysisplate_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositiveControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(shared.mixins.AdminUrlsMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name="plateposition",
            name="position_contain_marker_xor_raw_xor_reserved",
        ),
        migrations.AddField(
            model_name="plateposition",
            name="positive_control",
            field=models.ForeignKey(
                blank=True,
                help_text="Positive control type for reserved positions on analysis plates",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="positions",
                to="genlab_bestilling.positivecontrol",
            ),
        ),
        migrations.AddConstraint(
            model_name="plateposition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("sample_raw__isnull", False),
                        ("sample_marker__isnull", True),
                        ("is_reserved", False),
                        ("positive_control__isnull", True),
                    ),
                    models.Q(
                        ("sample_raw__isnull", True),
                        ("sample_marker__isnull", False),
                        ("is_reserved", False),
                        ("positive_control__isnull", True),
                    ),
                    models.Q(
                        ("sample_raw__isnull", True),
                        ("sample_marker__isnull", True),
                        ("is_reserved", True),
                    ),
                    models.Q(
                        ("sample_raw__isnull", True),
                        ("sample_marker__isnull", True),
                        ("is_reserved", False),
                        ("positive_control__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="position_contain_marker_xor_raw_xor_reserved",
            ),
        ),
    ]
