# Generated by Django 5.2.3 on 2026-03-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0051_add_positive_control"),
    ]

    operations = [
        migrations.AddField(
            model_name="plateposition",
            name="is_invalid",
            field=models.BooleanField(
                default=False, help_text="Mark this position as invalid"
            ),
        ),
    ]
