# Generated by Django 5.2.11 on 2026-04-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0052_add_position_is_invalid"),
    ]

    operations = [
        migrations.AddField(
            model_name="genrequest",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Archive the genetic project to hide it from the default list view",
            ),
        ),
    ]
