# Generated by Django 5.2.13 on 2026-05-03 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0053_add_is_archived_to_genrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysisorder",
            options={},
        ),
        migrations.AlterModelOptions(
            name="equipmentorder",
            options={},
        ),
        migrations.AlterModelOptions(
            name="extractionorder",
            options={},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterModelOptions(
            name="plate",
            options={},
        ),
    ]
