# Generated by Django 5.2.13 on 2026-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0054_alter_analysisorder_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="master_mix",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="marker",
            name="pcr_program",
            field=models.TextField(blank=True, null=True, verbose_name="PCR program"),
        ),
        migrations.AddField(
            model_name="marker",
            name="primer_concentration_um",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Primer concentration (µM)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="primer_pair_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="marker",
            name="primer_sequences",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marker",
            name="probe_concentration_um",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Probe concentration (µM)",
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="probe_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="marker",
            name="sop",
            field=models.TextField(
                blank=True, null=True, verbose_name="SOP (Standard Operating Procedure)"
            ),
        ),
        migrations.AddField(
            model_name="marker",
            name="total_volume_ul",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total volume (µL)",
            ),
        ),
    ]
