# Generated by Django 5.2.13 on 2026-07-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0055_add_marker_pcr_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisplate",
            name="billed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
