# Generated by Django 5.2.16 on 2026-08-11 08:41

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0056_analysisplate_billed_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"base_manager_name": "all_objects", "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="species",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["name"],
                "verbose_name_plural": "Species",
            },
        ),
        migrations.AlterModelManagers(
            name="area",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="species",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="area",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Hidden areas are excluded from forms and filters.",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Hidden species are excluded from forms and filters.",
            ),
        ),
    ]
