# Generated by Django 6.1 on 2026-08-12 09:08

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0057_alter_area_options_alter_species_options_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="area",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="species",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
