# Generated by Django 6.1 on 2026-08-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0058_alter_area_managers_alter_species_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Hidden areas are excluded from forms and filters.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Hidden species are excluded from forms and filters.",
                null=True,
            ),
        ),
    ]
