# Generated by Django 6.1 on 2026-10-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genlab_bestilling", "0059_alter_area_is_hidden_alter_species_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="external_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
