# Generated by Django 5.1.7 on 2025-05-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nina", "0002_alter_projectmembership_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
