# Generated by Django 5.2.13 on 2026-07-27 15:42

import shared.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nina", "0003_project_verified_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidProject",
            fields=[
                ("number", models.CharField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Valid Project",
                "verbose_name_plural": "Valid Projects",
            },
            bases=(shared.mixins.AdminUrlsMixin, models.Model),
        ),
    ]
