SAMPLE_CSV_FIELD_LABELS = {
    "genlab_id": "Genlab ID",
    "fish_id": "Old Genlab ID",
    "guid": "GUID",
    "name": "Name",
    "species.name": "Species",
    "location.name": "Location",
    "order": "EXT_order",
    "analysis_orders": "ANL_order",
    "pop_id": "PopID",
    "type.name": "Sample Type",
    "gender": "Gender",
    "length": "Length",
    "weight": "Weight",
    "classification": "Classification",
    "year": "Year",
    "notes": "Notes",
    "project": "Project Number",
    "isolation_method": "Isolation Method",
    "qiagen_number": "Qiagen#",
    "is_marked": "Marked",
    "is_plucked": "Plucked",
    "is_isolated": "Isolated",
    "station": "Station",
    "placement_in_fridge": "Placement in Fridge",
    "delivered_to_lab": "Delivered to Lab",
    "fluidigm#": "Fluidigm#",
    "laksov_species": "LaksOV + Species",
    "species_date": "Species Date",
    "pcr": "PCR",
    "fluidigm": "Fluidigm",
    "output": "Output",
    "analysis_note": "Analysis Note",
    "rerun": "Rerun",
    "rerun_qiagen": "Rerun Qiagen",
    "river": "River",
    "str_date": "STR Date",
    "rerun_date": "Rerun Date",
    "watercourse_number": "Watercourse Number",
    "under_locality": "Sub-locality",
    "county": "County",
    "snp_assay_1": "SNP Assay 1",
    "snp_assay_2": "SNP Assay 2",
    "str_mixab": "STR Mix AB",
    "str_mixc": "STR Mix C",
    "str_mixy": "STR Mix Y",
    "internal_note": "Internal Note",
    "bb#": "BB#",
    "output_bb": "Output",
    "bba2#": "BBA2#",
    "output_bba2": "Output",
    "mixab": "Mix AB",
    "ab_rep#": "AB Rep#",
    "mixc": "Mix C",
    "c_rep#": "C Rep#",
    "re_extracted_date": "Re-extracted Date",
    "re_extracted_qiagen#": "Re-extracted Qiagen#",
    "weight_g_for_diet_analysis": "Weight (g) for Diet Analysis",
    "position": "Position",
    "genlab_sample_id": "Genlab_sample_ID",
    "dna_extract_guid": "DNAextract_GUID",
}

SAMPLE_CSV_FIELDS_BY_AREA = {
    "Akvatisk": (
        "name",
        "genlab_id",
        "fish_id",
        "guid",
        "order",
        "analysis_orders",
        "location.name",
        "watercourse_number",
        "pop_id",
        "species.name",
        "gender",
        "length",
        "weight",
        "classification",
        "year",
        "notes",
        "project",
        "type.name",
        "isolation_method",
        "qiagen_number",
        "fluidigm#",
        "laksov_species",
        "species_date",
        "is_marked",
        "is_plucked",
        "is_isolated",
        "pcr",
        "fluidigm",
        "output",
        "analysis_note",
        "rerun",
        "rerun_date",
    ),
    "Elvemusling": (
        "name",
        "genlab_id",
        "fish_id",
        "guid",
        "order",
        "analysis_orders",
        "river",
        "location.name",
        "under_locality",
        "watercourse_number",
        "county",
        "year",
        "station",
        "type.name",
        "length",
        "notes",
        "isolation_method",
        "qiagen_number",
        "position",
        "placement_in_fridge",
        "is_marked",
        "is_plucked",
        "is_isolated",
        "pcr",
        "str_date",
        "output",
        "analysis_note",
        "rerun",
        "rerun_date",
    ),
    "Terrestrisk": (
        "name",
        "genlab_id",
        "guid",
        "type.name",
        "species.name",
        "location.name",
        "delivered_to_lab",
        "order",
        "analysis_orders",
        "notes",
        "snp_assay_1",
        "snp_assay_2",
        "str_mixab",
        "str_mixc",
        "str_mixy",
        "is_marked",
        "is_plucked",
        "is_isolated",
        "isolation_method",
        "qiagen_number",
        "internal_note",
        "bb#",
        "output_bb",
        "bba2#",
        "output_bba2",
        "mixab",
        "ab_rep#",
        "mixc",
        "c_rep#",
        "re_extracted_date",
        "re_extracted_qiagen#",
        "weight_g_for_diet_analysis",
    ),
    "MiljøDNA": (
        "genlab_id",
        "genlab_sample_id",
        "guid",
        "dna_extract_guid",
        "name",
        "type.name",
        "species.name",
        "location.name",
        "delivered_to_lab",
        "order",
        "analysis_orders",
        "notes",
        "is_marked",
        "is_plucked",
        "is_isolated",
        "isolation_method",
        "qiagen_number",
    ),
    "default": (
        "genlab_id",
        "guid",
        "name",
        "type.name",
        "species.name",
        "location.name",
        "order",
        "analysis_orders",
        "notes",
        "is_marked",
        "is_plucked",
        "is_isolated",
        "isolation_method",
        "qiagen_number",
    ),
}

LABEL_CSV_FIELDS_BY_AREA = {
    "Akvatisk": ("fish_id", "genlab_id", "guid"),
    "Elvemusling": ("fish_id", "genlab_id", "guid"),
    "Terrestrisk": ("genlab_id", "guid", "name"),
    "MiljøDNA": ("genlab_id", "guid", "name", "location.name"),
    "default": ("genlab_id", "guid", "name"),
}
