from django.urls import path

from staff.api import OrderAPIView

from .views import (
    AnalysisOrderDetailView,
    AnalysisOrderListView,
    AnalysisPlateCreateView,
    AnalysisPlateDetailView,
    AnalysisPlateListView,
    AnalysisPlatePositionsView,
    AnalysisPlateUpdateView,
    DashboardView,
    EquipmentOrderDetailView,
    EqupimentOrderListView,
    ExtractionOrderDetailView,
    ExtractionOrderListView,
    ExtractionPlateCreateView,
    ExtractionPlateDetailView,
    ExtractionPlateListView,
    ExtractionPlatePositionsView,
    ExtractionPlateUpdateView,
    GenerateGenlabIDsView,
    MarkAsSeenView,
    OrderAnalysisSamplesListView,
    OrderExtractionSamplesListView,
    OrderPrioritizedAdminView,
    OrderToDraftActionView,
    OrderToNextStatusActionView,
    ProjectArchiveActionView,
    ProjectDetailView,
    ProjectListView,
    ProjectValidateActionView,
    SampleDetailView,
    SampleLabView,
    SampleReplicaActionView,
    SamplesListView,
    StaffEditView,
    UpdateInternalNote,
)

app_name = "staff"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("projects/", ProjectListView.as_view(), name="projects-list"),
    path("projects/<str:pk>/", ProjectDetailView.as_view(), name="projects-detail"),
    path(
        "projects/<str:pk>/verify/",
        ProjectValidateActionView.as_view(),
        name="projects-verify",
    ),
    path(
        "projects/<str:pk>/archive/",
        ProjectArchiveActionView.as_view(),
        name="projects-archive",
    ),
    path(
        "orders/analysis/", AnalysisOrderListView.as_view(), name="order-analysis-list"
    ),
    path(
        "orders/equipment/",
        EqupimentOrderListView.as_view(),
        name="order-equipment-list",
    ),
    path(
        "orders/extraction/",
        ExtractionOrderListView.as_view(),
        name="order-extraction-list",
    ),
    path(
        "orders/analysis/<int:pk>/",
        AnalysisOrderDetailView.as_view(),
        name="order-analysis-detail",
    ),
    path(
        "orders/<int:pk>/to-draft/",
        OrderToDraftActionView.as_view(),
        name="order-to-draft",
    ),
    path(
        "orders/<int:pk>/to-next-status/",
        OrderToNextStatusActionView.as_view(),
        name="order-to-next-status",
    ),
    path(
        "<str:model_type>/<int:pk>/add-staff/",
        StaffEditView.as_view(),
        name="add-staff",
    ),
    path(
        "orders/extraction/<int:pk>/samples/",
        OrderExtractionSamplesListView.as_view(),
        name="order-extraction-samples",
    ),
    path(
        "orders/extraction/<int:pk>/samples/lab",
        SampleLabView.as_view(),
        name="order-extraction-samples-lab",
    ),
    path(
        "orders/extraction/<int:pk>/samples/generate-genlab-ids/",
        GenerateGenlabIDsView.as_view(),
        name="generate-genlab-ids",
    ),
    path(
        "orders/samples/update/internal-note/",
        UpdateInternalNote.as_view(),
        name="update-internal-note",
    ),
    path(
        "orders/analysis/<int:pk>/samples/",
        OrderAnalysisSamplesListView.as_view(),
        name="order-analysis-samples",
    ),
    path(
        "samples/",
        SamplesListView.as_view(),
        name="samples-list",
    ),
    path(
        "samples/<int:pk>/",
        SampleDetailView.as_view(),
        name="samples-detail",
    ),
    path(
        "samples/<int:pk>/replica/",
        SampleReplicaActionView.as_view(),
        name="samples-detail-replica",
    ),
    path(
        "orders/equipment/<int:pk>/",
        EquipmentOrderDetailView.as_view(),
        name="order-equipment-detail",
    ),
    path(
        "order/mark-as-seen/<int:pk>/",
        MarkAsSeenView.as_view(),
        name="mark-as-seen",
    ),
    path(
        "orders/extraction/<int:pk>/",
        ExtractionOrderDetailView.as_view(),
        name="order-extraction-detail",
    ),
    path(
        "extraction-plates/",
        ExtractionPlateListView.as_view(),
        name="extraction-plates-list",
    ),
    path(
        "extraction-plates/create/",
        ExtractionPlateCreateView.as_view(),
        name="extraction-plates-create",
    ),
    path(
        "extraction-plates/<uuid:pk>/",
        ExtractionPlateDetailView.as_view(),
        name="extraction-plates-detail",
    ),
    path(
        "extraction-plates/<uuid:pk>/update/",
        ExtractionPlateUpdateView.as_view(),
        name="extraction-plates-update",
    ),
    path(
        "analysis-plates/",
        AnalysisPlateListView.as_view(),
        name="analysis-plates-list",
    ),
    path(
        "analysis-plates/create/",
        AnalysisPlateCreateView.as_view(),
        name="analysis-plates-create",
    ),
    path(
        "analysis-plates/<uuid:pk>/",
        AnalysisPlateDetailView.as_view(),
        name="analysis-plates-detail",
    ),
    path(
        "analysis-plates/<uuid:pk>/update/",
        AnalysisPlateUpdateView.as_view(),
        name="analysis-plates-update",
    ),
    path(
        "orders/<int:pk>/priority/",
        OrderPrioritizedAdminView.as_view(),
        name="order-priority",
    ),
    path(
        "orders/<int:pk>/assign-staff/",
        OrderAPIView.as_view(),
        name="order-assign-staff",
    ),
    path(
        "extraction-plates/<uuid:pk>/positions/",
        ExtractionPlatePositionsView.as_view(),
        name="extraction-plates-positions",
    ),
    path(
        "analysis-plates/<uuid:pk>/positions/",
        AnalysisPlatePositionsView.as_view(),
        name="analysis-plates-positions",
    ),
]
